### ISSUE TITLE
No, absolutly not. Never push actual data to github.

### ISSUE THREAD

**Issue by agargiulo** [kdolan/RIDE#13]
Never push actual data to github, even if it's not passwords, usernames are still sensitive data.
https://github.com/kdolan/RIDE/blob/dfb6c6e5bafa17987041d53830caa2670e13c64b/scripts/func.php#L41

**Comment by worr** [comment]
Hold up.

Can we also talk about how you're hard-coding names and usernames? How would that ever scale?

**Comment by agargiulo** [comment]
Well, that too.

**Comment by rswiernik** [comment]
Scales right up!

**Comment by ryansb** [comment]
Somebody needs a :facepunch: for hardcoding user data.

**Comment by worr** [comment]
Ahem.

https://github.com/kdolan/RIDE/commit/763984a346ebf151160a7b8c7953667f477b5310

**Comment by kdolan** [comment]
Application is deprecated.
