### ISSUE TITLE
There's absolutely no SQL sanitization

### ISSUE THREAD

**Issue by worr** [kdolan/RIDE#14]
For example, you could go here and disable every single event (and email everyone who's ever used this damn thing).

```
https://ride.csh.rit.edu/scripts/sDisableEvent.php?eventId=20%20OR%201=1
```

I haven't tested (I'm not going to be a dick), but even if you need to be an admin, you're vulnerable to trivial CSRF.

``` html
<img src="https://ride.csh.rit.edu/scripts/sDisableEvent.php?eventId=20%20OR%201=1">
```

That will look like a broken image if you load it, but it will disable all of the events in the database as soon as someone with whatever privs views that image.

The right thing to do is to generate a CSRF token that has a limited lifetime and embed it as a hidden form, make this happen over a POST request (which sends the CSRF token), and set `X-Frame-Options: Deny`.

Oh, and sanitize and validate all of your inputs server-side.

**Comment by kdolan** [comment]
All input is sanitized via the secure input function. 

``` php
$eventId = secureInput($_GET["eventId"]);
```

``` php
//func.php
function secureInput($inputString)
{
      $safeString = mysql_real_escape_string($inputString);
      $safeString = preg_replace('#<script(.*?)>(.*?)</script>#is', '', $safeString);
      $safeString  = strip_tags($safeString);
      return $safeString;
}
```

Won't implement CSRF protection until I do a major re-write.

**Comment by worr** [comment]
Good effort! You did both things (sanitizing HTML and sanitizing SQL data) incorrectly though.

To sanitize HTML, generally you want to translate the data into HTML entities. [There's a PHP function that does this for you](http://us3.php.net/htmlentities) (make sure you read the note on ENT_QUOTES). Typically, you do this when outputting data to the page (ideally via use of templating). You don't lose any information, and you prevent XSS.

To sanitize SQL data, you want to use SQL parameterization. Both mysqli and PDO support this. The old mysql interface that you're using is deprecated, and iirc doesn't support this.
