### ISSUE TITLE
More ability to ride overview

### ISSUE THREAD

**Issue by JDrit** [kdolan/RIDE#4]
You make it so that you can view who created the event and allow the creator of the event to delete the event. This will help with the creating of the multiple events.

**Comment by agargiulo** [comment]
I believe you accidentally a word there. Did you mean, "You _should_ make it so..."?

**Comment by kdolan** [comment]
Event creator stored in database and creator does have ability to edit and will soon have ability to disable there event. Admins are also allowed to edit all events.
