### ISSUE TITLE
Drivers should not be able to add themselves their own ride. 

### ISSUE THREAD

**Issue by agargiulo** [kdolan/RIDE#6]
https://ride.csh.rit.edu/createRide.php?edit=1&eventId=17&carId=1

**Comment by kdolan** [comment]
That link actually illustrates another issue of the system not recognizing users. The user agargiulo was not added to that ride. The non-csher with full name 'agargiulo.' Was added to the ride. When I tried to add you to your own ride using the superbar it just errored out the driver. Thanks for finding this!
